---
title: "Preparing for Prelims!"
author: "Bradley M Richardson"
date: 2019-01-23T21:13:14-05:00
categories: ["Project Update"]
tags: ["aeromonas", "catfish", "dissertation"]
---

_Well, the time has officially arrived! Next week, I will begin my preliminary exams to fulfill my requirements to move from a Ph.D student to a Ph.D candidate! This means that starting on Monday, **I will start a week of written exams**, one from each of my dissertation committee members._

Over the last 2 months or so, I have been studying every aspect of biology, ecology, immunology, and aquaculture that relates to my research. On Monday, I will receive the first of 5 written exams. Each day, one of my committee members will provide me with exam questions of their choosing. **Any information that a biologist working in the fields of aquaculture, biology, and/or immunology would be expected to know is fair game!**

I will have 24 hours to complete each set of exam questions, then the next set will be provided and I will continue this process until I have completed an exam for each member. The set-up for preliminary exams is different for each student/committee, but my committee has decided on the following rules: **_1)** I will receive an exam each day and have 24 hours to complete it; **2)** I can use any materials that I have in hard copy or that are present on my computer; **3)** I am not allowed to access the internet to answer any questions._ I, personally, enjoy this set up because it allows my committee to ask more in-depth/rigorous questions and forces me to use the information I already know to synthesize the foundation of my answer. However, I still have the option to use other texts to bolster my answers and provide additional support.

After I have completed my written exams, my committee and I will meet on Feb. 14th to conduct the oral exam. **The oral exam will likely last 2-4 hours** and during that time the committee members have the chance to test my knowlege on any new material that they did not ask during their written exam, or ask me to provide more detail/clarification about an answer from the written responses.

Assuming I pass my exams, I will be admitted to Ph.D Candidate and I will be one step closer to being the first person in my family to complete a doctoral degree and reaching my goal of being a college professor! My expected graduation date is May 2020, so I am inching ever-closer to that point!

Thank you to everyone that has supported me along this journey, and wish me luck! Hopefully, I will be able to post some good news in the near future!!