---
title: "Summer Shenanigans"
author: "Bradley M Richardson"
date: 2019-08-20T21:13:14-05:00
categories: ["Project Update"]
tags: ["trematodes", "catfish", "morphometrics", "Mississippi"]
---


  So, my final summer as a PhD student just wrapped up and I have to say I'm pretty happy with how it turned out. This summer led to a wide range of new experiences, projects, and results. I have begun a collaboration with a parasitologist in the Mississippi State vet school, investigating trematode morphometrics for species identification. The parasitologist believes he has found several specimens that have been mis-identified, which has led to an artificial reduction in the diversity of this parasite genus. So, we are teaming up for a project using morphometrics and molecular data to determine the true identifications and (hopefully) update the key for this genus. After seeing the potential in this morphometric method, he has also mentioned looking at the morphometrics of some other organisms he has, so there will be much more to come on this topic in the future!